=== 0b3r/hello-retail/event-writer/schemas/retail-stream-schema-ingress.json
{
  "$schema": "http://json-schema.org/schema#",
  "self": {
    "vendor": "com.nordstrom",
    "name": "retail-stream-ingress",
    "format": "jsonschema",
    "version": "1-0-0"
  },
  "type": "object",
  "properties": {
    "schema":      { "type": "string", "format": "uri" },
    "followsFrom": { "type": "string", "pattern": "^shardId-\\d{12}:\\d{56}$" },
    "origin":      { "type": "string", "pattern": "^([\\w-. ]{1,128}\\/){3}[\\w-. ]{1,128}$" },
    "timeOrigin":  { "type": "string", "format": "date-time" },
    "data": {
      "type": "object",
      "properties": {
        "schema":  { "type": "string", "format": "uri" }
      },
      "required": [
        "schema"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "schema",
    "origin",
    "timeOrigin",
    "data"
  ],
  "additionalProperties": false
}

=== 0b3r/hello-retail/scripts/product-create-event.json
{
  "schema": "com.nordstrom/retail-stream-ingress/1-0-0",
  "origin": "scripts/put-retail-stream-event",
  "timeOrigin": "2017-02-21T23:27:56.673Z",
  "data": {
    "schema": "com.nordstrom/product/create/1-0-0",
    "id": "9000000",
    "brand": "Scripted Brand",
    "name": "Scripted Name",
    "description": "This product came from the put-retail-stream-event script.",
    "category": "Test Script Category"
  }
}
